// src/components/layout/TheFooter.tsx
import { useRouterState } from '@tanstack/react-router'
import EditIcon from '../icons/EditIcon'
import QuestionIcon from '../icons/QuestionIcon'
import BugIcon from '../icons/BugIcon'
import NetlifyBadge from '../NetlifyBadge'

type FooterProps = {
  repository?: string
}

export default function Footer({ repository = '' }: FooterProps) {
  const { location } = useRouterState()
  const routesWithoutGithub = ['/', '/blog']

  const editLink = {
    linkHeader: 'Edit this page on',
    linkText: 'GitHub',
    url: `${repository}${location.pathname}.md`,
    icon: EditIcon,
  }

  const footerLinks = [
    {
      linkHeader: 'Do you have a question?',
      linkText: 'ask the community',
      url: 'https://github.com/wilfredinni/javascript-cheatsheet/discussions',
      icon: QuestionIcon,
    },
    {
      linkHeader: 'Do you see a bug?',
      linkText: 'open an issue on GitHub',
      url: 'https://github.com/wilfredinni/javascript-cheatsheet/issues',
      icon: BugIcon,
    },
  ]

  const EditIconComponent = editLink.icon

  return (
    <footer className="mt-5 border-t dark:border-t-zinc-800">
      <div className="justify-between pt-5 sm:flex">
        <div
          className={`grid text-xs ${
            location.pathname !== '/' ? 'space-y-1.5' : ''
          }`}
        >
          {!routesWithoutGithub.includes(location.pathname) ? (
            <div className="flex items-center text-zinc-600 dark:text-zinc-400 font-medium">
              <EditIconComponent className="mr-2 h-4 w-4" />
              {editLink.linkHeader}
              <a
                target="_blank"
                href={editLink.url}
                className="ml-1 flex text-zinc-600 hover:text-zinc-800 dark:text-zinc-100 dark:hover:text-zinc-300"
                rel="noreferrer"
              >
                {editLink.linkText}
              </a>
            </div>
          ) : null}

          {footerLinks.map((link) => {
            const LinkIcon = link.icon
            return (
              <div
                key={link.url}
                className="flex items-center text-zinc-600 dark:text-zinc-400 font-medium"
              >
                <LinkIcon className="mr-2 h-4 w-4" />
                {link.linkHeader}
                <a
                  target="_blank"
                  href={link.url}
                  className="ml-1 flex text-zinc-600 hover:text-zinc-800 dark:text-zinc-100 dark:hover:text-zinc-300"
                  rel="noreferrer"
                >
                  {link.linkText}
                </a>
              </div>
            )
          })}
        </div>

        <div className="mt-4 grid sm:mt-0">
          <NetlifyBadge />
        </div>
      </div>
    </footer>
  )
}

// src/components/layout/TheFooter.vue
<script setup lang="ts">
import EditIcon from '~/components/icons/EditIcon.vue'
import QuestionIcon from '~/components/icons/QuestionIcon.vue'
import BugIcon from '~/components/icons/BugIcon.vue'

const props = defineProps<{
  repository?: string
}>()

const route = useRoute()

const EditLink = {
  linkHeader: 'Edit this page on',
  linkText: 'GitHub',
  url: `${props.repository}${route.path}.md`,
  icon: EditIcon,
}

const footerLinks = [
  {
    linkHeader: 'Do you have a question?',
    linkText: 'ask the community',
    url: 'https://github.com/wilfredinni/javascript-cheatsheet/discussions',
    icon: QuestionIcon,
  },
  {
    linkHeader: 'Do you see a bug?',
    linkText: 'open an issue on GitHub',
    url: 'https://github.com/wilfredinni/javascript-cheatsheet/issues',
    icon: BugIcon,
  },
]

const routesWithoutGithub = ['index', 'blog']
</script>

<template>
  <footer class="mt-5 border-t dark:border-t-zinc-800">
    <div class="justify-between pt-5 sm:flex">
      <div
        class="grid text-xs"
        :class="route.name !== 'index' ? 'space-y-1.5' : ''"
      >
        <div
          v-if="!routesWithoutGithub.includes(route.name as string)"
          class="flex items-center text-zinc-600 dark:text-zinc-400 font-medium"
        >
          <component :is="EditLink.icon" class="mr-2 h-4 w-4" />
          {{ EditLink.linkHeader }}
          <a
            target="_blank"
            :href="`${repository}${$route.path}.md`"
            class="ml-1 flex text-zinc-600 hover:text-zinc-800 dark:text-zinc-100 dark:hover:text-zinc-300"
          >
            {{ EditLink.linkText }}
          </a>
        </div>

        <div
          v-for="link in footerLinks"
          v-once
          :key="link.url"
          class="flex items-center text-zinc-600 dark:text-zinc-400 font-medium"
        >
          <component :is="link.icon" class="mr-2 h-4 w-4" />
          {{ link.linkHeader }}
          <a
            target="_blank"
            :href="link.url"
            class="ml-1 flex text-zinc-600 hover:text-zinc-800 dark:text-zinc-100 dark:hover:text-zinc-300"
          >
            {{ link.linkText }}
          </a>
        </div>
      </div>

      <div class="mt-4 grid sm:mt-0">
        <netlify-badge class="mx-auto" />
      </div>
    </div>
  </footer>
</template>
