// src/components/layout/TheNavbarReader.tsx
import BaseThemeToggle from '../ui/BaseThemeToggle'
import { useReader } from '../../context/reader'

export default function NavbarReader() {
  const reader = useReader()

  const fontIndex = reader.fontSizes.findIndex(
    (item) => item === reader.fontSize,
  )
  const hasNext = reader.fontSizes.length - 1 > fontIndex
  const hasPrevious = fontIndex !== 0

  const increaseFont = () => {
    if (hasNext) {
      reader.setFontSize(reader.fontSizes[fontIndex + 1])
    }
  }

  const decreaseFont = () => {
    if (hasPrevious) {
      reader.setFontSize(reader.fontSizes[fontIndex - 1])
    }
  }

  return (
    <nav className="sticky top-0 z-40 w-full flex-none border-b border-zinc-900/10 bg-white/80 backdrop-blur dark:border-zinc-50/6 dark:bg-zinc-900/80 lg:z-50">
      <div className="mx-auto max-w-8xl px-4 xl:px-10">
        <div className="relative flex h-16 justify-between">
          <div className="flex flex-1 items-center justify-end space-x-5 sm:items-center">
            <div className="ml-6 space-x-6 border-r border-zinc-200 pr-6 dark:border-zinc-800">
              <button
                className={`text-zinc-400 transition duration-300 dark:text-zinc-500 ${
                  hasNext
                    ? 'hover:text-amber-500 dark:hover:text-amber-500'
                    : ''
                }`}
                onClick={increaseFont}
              >
                A+
              </button>
              <button
                className={`text-zinc-400 transition duration-300 dark:text-zinc-500 ${
                  hasPrevious
                    ? 'hover:text-amber-500 dark:hover:text-amber-500'
                    : ''
                }`}
                onClick={decreaseFont}
              >
                A-
              </button>
              <span className="text-white"> </span>
            </div>

            <BaseThemeToggle />

            <button
              className="rounded text-zinc-400 transition duration-300 hover:text-amber-500 dark:hover:bg-transparent"
              onClick={reader.toggle}
            >
              <span className="sr-only">close reader mode</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </nav>
  )
}

// src/components/layout/TheNavbarReader.vue
<script setup lang="ts">
const reader = useReaderStore()

const fontIndex = computed(() => {
  return reader.fontSizes.findIndex((item) => item === reader.fontSize)
})

const hasNext = computed(() => reader.fontSizes.length - 1 > fontIndex.value)
const increaseFont = () => {
  if (hasNext.value) {
    reader.setFontSize(reader.fontSizes[fontIndex.value + 1])
  }
}

const hasPrevious = computed(() => fontIndex.value !== 0)
const decreaseFont = () => {
  if (hasPrevious.value) {
    reader.setFontSize(reader.fontSizes[fontIndex.value - 1])
  }
}
</script>

<template>
  <nav
    class="sticky top-0 z-40 w-full flex-none bg-transparent backdrop-blur dark:border-zinc-50/[0.06] lg:z-50 lg:border-b lg:border-zinc-900/10"
  >
    <div class="mx-auto max-w-8xl px-4 xl:px-10">
      <div class="relative flex h-14 justify-between">
        <div
          class="flex flex-1 items-center justify-end space-x-5 sm:items-center"
        >
          <div
            class="ml-6 space-x-6 border-r border-zinc-200 dark:border-zinc-800"
          >
            <button
              class="text-zinc-400 transition duration-300 dark:text-zinc-500"
              :class="
                hasNext ? 'hover:text-amber-500 dark:hover:text-amber-500' : ''
              "
              @click="increaseFont"
            >
              A+
            </button>
            <button
              class="text-zinc-400 transition duration-300 dark:text-zinc-500"
              :class="
                hasPrevious
                  ? 'hover:text-amber-500 dark:hover:text-amber-500'
                  : ''
              "
              @click="decreaseFont"
            >
              A-
            </button>
            <span class="text-white"> </span>
          </div>

          <base-theme-toggle />

          <button
            class="rounded text-zinc-400 transition duration-300 hover:text-amber-500 dark:hover:bg-transparent"
            @click="reader.toggle()"
          >
            <span class="sr-only">close reader mode</span>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-width="2"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>
