// src/components/ui/BaseLinkCard.vue
<script setup lang="ts">
defineProps<{
  icon: Object
  path: string
  title: string
  description: string
  isExternal?: boolean
}>()
</script>

<template>
  <div
    class="group relative rounded-xl border border-zinc-200 dark:border-zinc-800"
  >
    <div
      class="absolute -inset-px rounded-xl border-2 border-transparent opacity-0 transition duration-200 [background:linear-gradient(var(--link-grid-hover-bg,theme(colors.zinc.50)),var(--link-grid-hover-bg,theme(colors.zinc.50)))_padding-box,linear-gradient(to_top,theme(colors.gray.400),theme(colors.neutral.400),theme(colors.zinc.500))_border-box] group-hover:opacity-100 dark:[--link-grid-hover-bg:theme(colors.slate.800)]"
    />
    <div class="relative overflow-hidden rounded-xl p-6">
      <component :is="icon" class="h-8 w-8" />
      <p class="mt-4 font-display text-base text-zinc-900 dark:text-white">
        <a v-if="isExternal" target="_blank" :href="path">
          <span class="absolute -inset-px rounded-xl" />
          {{ title }}
        </a>
        <router-link v-else :to="path">
          <span class="absolute -inset-px rounded-xl" />
          {{ title }}
        </router-link>
      </p>
      <p class="mt-1 text-sm text-zinc-700 dark:text-zinc-400">
        {{ description }}
      </p>
    </div>
  </div>
</template>

// src/components/ui/BaseLinkCard.tsx
import type { ComponentType } from 'react'
import { Link } from '@tanstack/react-router'

type IconComponent = ComponentType<{ className?: string }>

type BaseLinkCardProps = {
  icon: IconComponent
  path: string
  title: string
  description: string
  isExternal?: boolean
}

export default function BaseLinkCard({
  icon: Icon,
  path,
  title,
  description,
  isExternal,
}: BaseLinkCardProps) {
  return (
    <div className="group relative rounded-xl border border-zinc-200 dark:border-zinc-800">
      <div className="absolute -inset-px rounded-xl border-2 border-transparent opacity-0 transition duration-200 [background:linear-gradient(var(--link-grid-hover-bg,theme(colors.zinc.50)),var(--link-grid-hover-bg,theme(colors.zinc.50)))_padding-box,linear-gradient(to_top,theme(colors.gray.400),theme(colors.neutral.400),theme(colors.zinc.500))_border-box] group-hover:opacity-100 dark:[--link-grid-hover-bg:theme(colors.slate.800)]" />
      <div className="relative overflow-hidden rounded-xl p-6">
        <Icon className="h-8 w-8" />
        <p className="mt-4 font-display text-base text-zinc-900 dark:text-white">
          {isExternal ? (
            <a target="_blank" rel="noreferrer" href={path}>
              <span className="absolute -inset-px rounded-xl" />
              {title}
            </a>
          ) : (
            <Link to={path}>
              <span className="absolute -inset-px rounded-xl" />
              {title}
            </Link>
          )}
        </p>
        <p className="mt-1 text-sm text-zinc-700 dark:text-zinc-400">
          {description}
        </p>
      </div>
    </div>
  )
}
